# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-27 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coach_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='教练名称'),
        ),
    ]
