# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-27 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverSchool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverschool',
            options={'verbose_name': '驾校机构', 'verbose_name_plural': '驾校机构'},
        ),
        migrations.AlterField(
            model_name='coach',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='城市编码'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='lati_td',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='long_td',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度'),
        ),
    ]
