# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-26 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradApp', '0002_auto_20180323_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach_orders',
            name='coupon',
        ),
        migrations.AddField(
            model_name='coach_orders',
            name='coupon_cn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='优惠劵号'),
        ),
    ]
